version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: peek_emission_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=peek_emission
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    cap_add:
      - SYS_NICE
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peek_emission_server
    restart: always
    depends_on:
      - db
    ports:
      - "${PORT}:8000"
    env_file:
      - .env

  # pma:
  #   image: phpmyadmin
  #   container_name: peek_emission_pma
  #   restart: always
  #   ports:
  #     - "${PHPMYADMIN_EXTERNAL_PORT}:80"
  #   logging:
  #     driver: none
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_ABSOLUTE_URI=${PMA_URI}
  #   env_file:
  #     - .env

volumes:
  postgres_data: